### ISSUE TITLE
Can use symsynd with ncurses 6

### ISSUE THREAD

**Issue by arthru** [getsentry/symsynd#6]
I tried to upgrade Sentry on my Arch Linux system and it appears that symsyng (sentry dependency) could not be installed on Arch Linux as its ncurses version is 6.0.

Symsynd seems to be linked against libncurses.so.5, but I could not find any reference to ncurses in symsynd project...

Below is the stack trace I got when running `sentry upgrade` :

```
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/utils/raven.py", line 78, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/db/models/manager.py", line 263, in get_from_cache
    result = self.get(**kwargs)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    if not can_reconnect(e):
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/db/postgres/helpers.py", line 20, in can_reconnect
    exc_msg = six.text_type(exc)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
10:57:21 [ERROR] sentry.errors: Unable to fetch internal project for some unknown reason
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/symsynd/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/runner/__init__.py", line 159, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/runner/__init__.py", line 122, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/runner/settings.py", line 160, in configure
    on_configure({'settings': settings})
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/runner/initializer.py", line 451, in on_configure
    settings, 'social_auth', 'social_auth_association')
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/runner/initializer.py", line 425, in skip_migration_if_applied
    migration = Migrations(app_name)[name]
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/south/migration/utils.py", line 41, in app_label_to_app_module
    app = models.get_app(app_label)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/loading.py", line 179, in get_app
    self._populate()
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/db/models/loading.py", line 97, in load_app
    app_module = import_module(app_name)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/lang/native/__init__.py", line 5, in <module>
    from .plugin import NativePlugin
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/lang/native/plugin.py", line 12, in <module>
    from sentry.lang.native.symbolizer import Symbolizer
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/lang/native/symbolizer.py", line 5, in <module>
    from symsynd.driver import Driver, SymbolicationError
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/../symsynd/driver.py", line 9, in <module>
    from symsynd.libsymbolizer import Symbolizer
  File "/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/../symsynd/libsymbolizer.py", line 9, in <module>
    lib = ffi.dlopen(os.path.join(os.path.dirname(__file__), '_libsymbolizer.so'))
OSError: cannot load library '/home/arthur/.virtualenvs/symsynd/lib/python2.7/site-packages/sentry/../symsynd/_libsymbolizer.so': libncurses.so.5: cannot open shared object file: No such file or directory
```

My virtualenv is a Python 2.7.12 one.

**Comment by s0undt3ch** [comment]
Exactly the same here.

**Comment by s0undt3ch** [comment]
Solution:

```
pacman -Sy cmake slang
pip install -U --no-binary=:all: symsynd
```

Be prepared to wait for quite a while...

**Comment by Forever-Young** [comment]
`clang` rather

**Comment by s0undt3ch** [comment]
Woops, yes, typo :smile:

**Comment by mitsuhiko** [comment]
There is not much I can do about this other than telling you to install ncurses 5 unfortunately. I am pretty sure statically linking in ncurses would be an issue.

**Comment by arthru** [comment]
I confirm that @s0undt3ch solution works.

As it works with both ncurses 5 and 6, the solution could be to link against libncurses.so and not libncurses.so.5 ?

But I just can't find where that linking is made...

**Comment by s0undt3ch** [comment]
Most distros are probably still using ncurses 5? So, perhaps, make this just a FAQ item? Or troubleshoot?

**Comment by mitsuhiko** [comment]
Linking against libncurses itself would be a violation of the manylinux spec. https://www.python.org/dev/peps/pep-0513/

That said, i wonder why we use libncurses.so.5 instead of libncursesw.so.5 and are getting away with it.

**Comment by mitsuhiko** [comment]
Closing this. Unlikely to be fixed
